### ISSUE TITLE
what is the pytorch version ?

### ISSUE THREAD

**Issue by guiyuliu** [ahmedius2/Human-Action-Recognition-using-Dense-LSTM#1]

**Comment by guiyuliu** [comment]
I run this file , MSR3DLSTM.ipynb,chage it to python file ,
it always occurrs the error 
```
Traceback (most recent call last):
  File "/home/lgy/workspace/Human-Action-Recognition-using-Dense-LSTM/msr.py", line 161, in <module>
    results = model(batch)
  File "/home/lgy/anaconda2/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgy/workspace/Human-Action-Recognition-using-Dense-LSTM/sbu.py", line 106, in forward
    self.hidden[0]
  File "/home/lgy/anaconda2/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lgy/anaconda2/envs/pytorch36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/home/lgy/anaconda2/envs/pytorch36/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 323, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/lgy/anaconda2/envs/pytorch36/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 287, in forward
    dropout_ts)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
```

**Comment by ahmedius2** [comment]
I have never seen an error like this on my system (Ubuntu 16.04 64 bit, Quadro K620 GPU). Maybe you should look this post : [https://discuss.pytorch.org/t/cudnn-status-execution-failed/4441/7](https://discuss.pytorch.org/t/cudnn-status-execution-failed/4441/7
)

**Comment by Jack-73** [comment]
Q1: Why do you build  tuple which is called  edgesBetweenJoints in your program of dataUtils? I don't find where  you have used this tuple.
Q2: What's the differences between the function of 'readMSRDataset' and 'readMSRDatasetCrossSubject'? These two function have many similar places and repeated parts.
Q3: I can't understand your function of organizeSkeletonData. What's the mean of 11Data、rlData、laData、raData、sData. Could you show me the function of organizeSkeletonData in detail?
Looking forward to your reply! Thank you!

**Comment by Jack-73** [comment]
How to understand your definition of cross subject?
